<a href="https://colab.research.google.com/github/Takiramen/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment3_ipynbTaki.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

# Discussion


In [10]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

### Matrices

The notation and use of matrices is probably one of the fundamentals of modern computing. Matrices are also handy representations of complex equations or multiple inter-related equations from 2-dimensional equations to even hundreds and thousands of them.

Let's say for example you have $A$ and $B$ as system of equation.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        1x - 2y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -4y -z \\
        -x + 5y +6z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent them as matrices as:

$$
A=\begin{bmatrix} 1 & 2 \\ 3 & {-4}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 2 & -2 & -2 \\ -3 & 3 & 3\end{bmatrix}
$$

So assuming that you already discussed the fundamental representation of matrices, their types, and operations. We'll proceed in doing them in here in Python.

### Declaring Matrices

Just like our previous laboratory activity, we'll represent system of linear equations as a matrix. The entities or numbers in matrices are called the elements of a matrix. These elements are arranged and ordered in rows and columns which form the list/array-like structure of matrices. And just like arrays, these elements are indexed according to their position with respect to their rows and columns. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.<br>
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices as vectors but we'll further discuss them in this laboratory activity. Since you already know how to describe vectors using <b>shape</b>, <b>dimensions</b> and <b>size</b> attributes, we'll use them to analyze these matrices.

In [11]:
## Since we'll keep on describing matrices. Let's make a function.
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [12]:
## Declaring a 2 x 2 matrix
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [13]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [14]:
## Declaring a 3 x 2 matrix
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [15]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



## Categorizing Matrices

There are several ways of classifying matrices. Once could be according to their <b>shape</b> and another is according to their <b>element values</b>. We'll try to go through them.

### According to shape

#### Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [16]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [17]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



#### Square Matrices

Square matrices are matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [18]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [19]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



### According to element values

#### Null Matrix

A Null Matrix is a matrix that has no elements. It is always a subspace of any vector or matrix.

In [20]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [21]:
null_mat = np.array([])
describe_mat(null_mat)


Matrix is Null


*italicized text*#### Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [22]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


#### Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [23]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

In [24]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [25]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]

False

#### Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal. 

In [28]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])



```
# This is formatted as code
```

#### Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [29]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

## Practice

1. Given the linear combination below, try to create a corresponding matrix representing it.

$$\theta = 5x + 3y - z$$

2. Given the system of linear combinations below, try to 

1.   List item
2.   List item

encode it as a matrix. Also describe the matrix.

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

3. Given the matrix below, express it as a linear combination in a markdown.

In [30]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

4. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [31]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

# Matrix Algebra

### Addition


In [32]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])
B = np.array([
    [2,2],
    [0,0],
    [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [33]:
2+A ##Broadcasting
# 2*np.ones(A.shape)+A

array([[3, 4],
       [4, 5],
       [6, 3]])

### Subtraction

In [34]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [35]:
3-B == 3*np.ones(B.shape)-B

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

### Element-wise Multiplication

In [36]:
A*B
np.multiply(A,B)

array([[2, 4],
       [0, 0],
       [4, 1]])

In [37]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [38]:
A@B


ValueError: ignored

In [39]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [40]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

## Activity

In [ ]:
### Task 1

Create a function named mat_desc() that througouhly describes a matrix, it should:

Displays the shape, size, and rank of the matrix.
Displays whether the matrix is square or non-square.
Displays whether the matrix is an empty matrix.
Displays if the matrix is an identity, ones, or zeros matrix
Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [41]:
## Function Area
import numpy as np


In [42]:
## Matrix Declarations

def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is a ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is a zeros matrix')
    else:
        print('The matrix is not a zeros matrix')

In [43]:
## Sample Matrices
print('Matrix 1:')
mat_desc([[0,0,0,0], [0, 0, 0,0], [0,0,0,0]])
print('Matrix 2:')
mat_desc([[4, 3, 0, 1], [2, 6, 2,5], [7, 1, 2, 8]])
print('Matrix 3:')
mat_desc([[1, 3, 2, 2], [4, 7, 6, 2], [5, 6, 9, 4]])
print('Matrix 4:')
mat_desc([[1,1,1],[1,1,1],[1,1,1],[1,1,1], [1,1,1]])
print('Matrix 5:')
mat_desc([[7,1,5,0],[1,6,2,0],[4,8,6,9],[7,2,1,0],[1,9,1,5]])

Matrix 1:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Shape: (3, 4)
Size: 12
Rank: 0
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is a zeros matrix
Matrix 2:
[[4 3 0 1]
 [2 6 2 5]
 [7 1 2 8]]
Shape: (3, 4)
Size: 12
Rank: 3
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 3:
[[1 3 2 2]
 [4 7 6 2]
 [5 6 9 4]]
Shape: (3, 4)
Size: 12
Rank: 3
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix
Matrix 4:
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Shape: (5, 3)
Size: 15
Rank: 1
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is a ones matrix
The matrix is not a zeros matrix
Matrix 5:
[[7 1 5 0]
 [1 6 2 0]
 [4 8 6 9]
 [7 2 1 0]
 [1 9 1 5]]
Shape: (5, 4)
Size: 20


### Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:

Determines if the matrices are viable for operation and returns your own error message if they are not viable.
Returns the sum of the matrices.
Returns the differen of the matrices.
Returns the element-wise multiplication of the matrices.
Returns the element-wise division of the matrices.
Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [44]:
## Function Area
import numpy as np

In [45]:
def mat_operations(mat1, mat2):
    mat1 = np.array(mat1)
    mat2 = np.array(mat2)
    print('Matrix 1:', mat1)
    print('Matrix 2:', mat2)
    if(mat1.shape != mat2.shape):
        print('The matrices are not equal and invalid size operation.')
        return
    print('Sum of the  matrices:')
    matsum = mat1 + mat2
    print(matsum)
    print('Difference of the  matrices:')
    matdiff = mat1 - mat2
    print(matdiff)
    print('Element-wise multiplication of the  matrices:')
    matmul = np.multiply(mat1, mat2)
    print(matmul)
    print('Element-wise division of the  matrices:')
    matdiv = np.divide(mat1, mat2)
    print(matdiv)

In [46]:
print('sample1:')
mat_operations([[2,3,2], [5,4,7], [4,3,8]],[[3,4,5], [9,7,1],[1,2,6]])

print('sample 2:')
mat_operations([[2, 6, 3,4], [3,3,1,5], [5,1,5,7]], [[3,7,5,7],[1,2,1,9],[1,1,1,6]])

print('sample 3:')
mat_operations([[2, 5, 1], [3,6,3], [6,1,5]], [[5,4,2],[3,4,6],[3,2,3]])

print('sample 4:')
mat_operations([[6,2,1,8,2], [3,6,3,7,8], [6,1,5,9,2]], [[5,4,2,7,7],[3,4,6,8,9],[3,2,3,6,2]])

print('sample 5:')
mat_operations([[6,2,1,8,2,5], [3,6,3,7,8,8], [6,1,5,9,2,2]], [[5,4,2,7,7,8],[3,4,6,8,9,2],[3,2,3,6,2,1]])


sample1:
Matrix 1: [[2 3 2]
 [5 4 7]
 [4 3 8]]
Matrix 2: [[3 4 5]
 [9 7 1]
 [1 2 6]]
Sum of the  matrices:
[[ 5  7  7]
 [14 11  8]
 [ 5  5 14]]
Difference of the  matrices:
[[-1 -1 -3]
 [-4 -3  6]
 [ 3  1  2]]
Element-wise multiplication of the  matrices:
[[ 6 12 10]
 [45 28  7]
 [ 4  6 48]]
Element-wise division of the  matrices:
[[0.66666667 0.75       0.4       ]
 [0.55555556 0.57142857 7.        ]
 [4.         1.5        1.33333333]]
sample 2:
Matrix 1: [[2 6 3 4]
 [3 3 1 5]
 [5 1 5 7]]
Matrix 2: [[3 7 5 7]
 [1 2 1 9]
 [1 1 1 6]]
Sum of the  matrices:
[[ 5 13  8 11]
 [ 4  5  2 14]
 [ 6  2  6 13]]
Difference of the  matrices:
[[-1 -1 -2 -3]
 [ 2  1  0 -4]
 [ 4  0  4  1]]
Element-wise multiplication of the  matrices:
[[ 6 42 15 28]
 [ 3  6  1 45]
 [ 5  1  5 42]]
Element-wise division of the  matrices:
[[0.66666667 0.85714286 0.6        0.57142857]
 [3.         1.5        1.         0.55555556]
 [5.         1.         5.         1.16666667]]
sample 3:
Matrix 1: [[2 5 1]
 [3 6 3]
 [6 1

## Conclusion


To further conclude this activity, the programmers have learned various ways of encoding matrices and have a good understanding of the definitions and types of matrices that can be used more easily than using handwritten algebraic expressions to further utilize the technology using computers and Google Colab. Moreover, this activity proves that matrices are used for shortcuts in Differential equations and a basic concept to use for the upcoming Chemical Engineers in creating prototypes for analysis specifically in the industry. Furthermore, the use of Matrix Algebra might be convenient for using different equations and for presentations for planning. In the world of Industrial Revolution 4.0, the utilization of advanced technologies is so predominant that it can easily manifest a lot of ideas and can further develop experiments in the future. At this point, as a good background in Mathematics along with technological devices, students and even experts could easily manipulate different approaches in applying matrices for Mathematics and this could lead to a more advanced and progress to another stepping stone towards the human race. In addition, [2]Digital picture is a matrix when it comes to the use of matrices in graphics. In basic terms, the matrix's rows and columns correspond to the pixels' rows and columns. The number entries correspond to the color codes of the pixels. Aside from that, matrices are employed to depict graphs. Meaning, every graph can be represented as a matrix, with each column and row representing a network point, and the value of their intersection representing the link between them.[3] Moreover, Matrices works also in the automation of Encryption of data, 3D games, economics and business, Construction, Dance, Animation, Physics, and Geology, which are fundamental in the 21st Century as their worldwide application of science. 
